#! /bin/bash
t=`awk '/Invalid user/{ip[$NF]++}END{for(i in ip){print ip[i],i}}' /var/log/secure | awk '$1>3{print $2}'`
echo "有人正在猜测你的用户名,ip为:$t" |mail -s "someone guess your username" root
t2=`awk '/Failed password/{ip2[$11]++}END{for(i in ip2){print ip2[i],i}}' /var/log/secure | awk '$1>3{print $2}'`
echo "有人正在猜测你的密码,ip为:$t2" |mail -s "someone guess your password" root
